config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'schedules#index'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :groups
  resources :schedules do
    collection do
      get 'all_schedules'
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :group_schedules, dependent: :destroy
  has_many :schedules, through: :group_schedules
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    Group.create(group_params)
    redirect_to groups_path
  end

  def show
  end

  def edit
  end

  def update
    @group.update(group_params)
    redirect_to group_path(@group.id)
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="main-wrapper">
  <%= form_with model: @group, url: group_path, local: true do |f| %>
    <div class="group">
      <%= f.label 'グループ名' %>
      <%= f.text_field :name %>
    </div>
    <div class="btns">
      <%= f.submit '確定する', class: "submit" %>
      <%= link_to '削除する', group_path(@group.id), method: :DELETE, class:"btn" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="main-wrapper">
  <h3 class="page-title">グループ一覧</h3>
  <div class="table">
    <% @groups.each do |g| %>
      <div class="table-row">
          <div class="table-row-left">
          <p><%= link_to g.name, group_path(g.id) %></p>
          </div>
        <div class="table-row-right">
          <%# グループ内のユーザーの名前をすべて取得 %>
          <% g.users.each do |u| %>
            <p><%= link_to u.name, user_path(u.id) %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="bottom btns">
    <p><%= link_to '新規グループ作成', new_group_path, class:"btn" %></p>
  </div>
</div>

app/views/groups/new.html.erb
<h1>groups # new</h1>

<%= form_with model: @group, url: groups_path, local: true do |f| %>
  <%= f.label 'グループ名' %>
  <%= f.text_field :name %>
  <%= f.submit '登録'%>
<% end %>

app/views/groups/show.html.erb
<div class="main-wrapper">
  <h3 class="page-title">
    <p>グループ情報：<%= @group.name %></p>
  </h3>
  <div class="table">
    <div class="table-row">
      <div class="table-row-left">
        <% @group.users.each do |u| %>
          <p><%= link_to u.name, user_path(u.id) %></p>
        <% end %>
        <% if @group.users == [] %>
          <p>所属している人はいません</p>
        <% end %>
      </div>
      <div class="table-row-right">
      </div>
    </div>
  </div>

  <div class="bottom btns">
    <p><%= link_to 'グループ情報を編集する', edit_group_path(@group.id), class:"btn" %></p>
    <p><%= link_to 'グループ一覧へ戻る', groups_path, class:"btn" %></p>
  </div>
</div>