config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'schedules#index'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :groups
  resources :schedules do
    collection do
      get 'all_schedules'
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :start
    validates :end
  end

  has_many :user_schedules, dependent: :destroy
  has_many :users, through: :user_schedules
  has_many :group_schedules, dependent: :destroy
  has_many :groups, through: :group_schedules
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :set_new_schedule, only: [:index, :new]
  before_action :set_users, only: [:index, :new, :edit]
  # before_action :set_groups, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    
    schedules_in_group = Schedule.where(id: GroupSchedule.select(:schedule_id))
    @schedules_not_in_group = Schedule.where.not(id: schedules_in_group.ids)
    @groups = Group.all
  end

  def all_schedules
    all_schedules = Schedule.all.to_a
    render json:{ all_schedules: all_schedules }
  end

  def new
    redirect_to root_path
  end

  def create
    #まずスケジュールのみ作成
    @schedule = Schedule.new(schedule_params)
    @schedule.save
    #その後ユーザーとの中間テーブルを作成。user_idsに含まれる空文字を除外してから、user_idひとつずつに@scheduleのidと紐付けたレコードを作成。
    user_schedules_params[:user_ids].compact_blank.each do |p|
      @schedule.user_schedules.create(user_id: p)
    end
    #ユーザーと同じことをグループでも行う。
    group_schedules_params[:group_ids].compact_blank.each do |p|
      @schedule.group_schedules.create(group_id: p)
    end
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    #まずスケジュールを更新
    @schedule.update(schedule_params)
    #スケジュールがもつユーザー情報を一旦すべて削除
    @schedule.user_schedules.destroy_all
    #user_idを再登録。user_idsに含まれる空文字を除外してから、user_idひとつずつに@scheduleのidと紐付けたレコードを作成。
    user_schedules_params[:user_ids].compact_blank.each do |p|
      @schedule.user_schedules.create(user_id: p)
    end
    #ユーザーと同じことをグループでも行う。
    @schedule.group_schedules.destroy_all
    group_schedules_params[:group_ids].compact_blank.each do |p|
      @schedule.group_schedules.create(group_id: p)
    end
    redirect_to schedule_path(params[:id])
  end

  def destroy
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:name, :start, :end, :place, :description)
  end

  def user_schedules_params
    params.require(:schedule).require(:user_schedules).permit(user_ids: [])
  end

  def group_schedules_params
    params.require(:schedule).require(:group_schedules).permit(group_ids: [])
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def set_new_schedule
    # 新規登録用に仮のインスタンスを作成
    @new_schedule = Schedule.new
  end

  def set_users
    #編集権限のないユーザーを取得
    @ordinaly_users = User.where(can_edit: false)
    #編集権限のあるユーザーを取得
    @editors = User.where(can_edit: true)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<h1>schedules # edit</h1>

<%= form_with model: @schedule, url: schedule_path, local: true do |f| %>
  <p>
    <%= f.label '予定名' %>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label '開始日時' %>
    <%= f.datetime_local_field :start %>
  </p>
  <p>
    <%= f.label '終了日時' %>
    <%= f.datetime_local_field :end %>
  </p>
  <p>
    <%= f.label '場所' %>
    <%= f.text_field :place %>
  </p>
  <p>
    <%= f.label 'メモ' %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.fields_for :user_schedules do |u| %>
      <p>
        <%= f.label '参加管理者' %>
        <%= u.collection_check_boxes :user_ids, @editors, :id, :name%>
      </p>
      <p>
        <%= f.label '参加利用者' %>
        <%= u.collection_check_boxes :user_ids, @ordinaly_users, :id, :name%>
      </p>
    <% end %>
  </p>
  <p>
    <%= f.fields_for :group_schedules do |g| %>
      <%= f.label 'グループ' %>
      <%= g.collection_check_boxes :group_ids, Group.all, :id, :name %>
    <% end %>
  </p>
  <p>
    <%= f.submit '登録' %>
  </p>
<% end %>

<p><%= link_to '削除', schedule_path(@schedule.id), method: :DELETE %></p>

app/views/schedules/index.html.erb
<%= javascript_pack_tag "index" %>

  <%# 2022/11/15 トップページから予定追加が可能であるため、newアクションへのリンクは表示しない。  %>
  <% if false %>
    <p><%= link_to '予定追加', new_schedule_path, class:"btn" %></p>
  <% end %>

<div class="schedules-wrapper">
  <div class="add_schedule">
    <p>予定を追加</p>
    <%= form_with model:@new_schedule, url: schedules_path, local: true do |f| %>
    <div class="schedule">
      <%= f.label '予定名' %>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="start">
      <%= f.label '開始日時' %>
      <%= f.datetime_local_field :start %>
    </div>
    <div class="end">
      <%= f.label '終了日時' %>
      <%= f.datetime_local_field :end %>
    </div>
    <div class="place">
      <%= f.label '場所' %>
      <%= f.text_field :place %>
    </div>
    <div class="description">
      <%= f.label 'メモ' %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.fields_for :user_schedules do |u| %>
        <div class="editors">
          <%= f.label '参加管理者' %>
          <%= u.collection_check_boxes :user_ids, @editors, :id, :name%>
        </div>
        <div class="ordinaly_users">
          <%= f.label '参加利用者' %>
          <%= u.collection_check_boxes :user_ids, @ordinaly_users, :id, :name%>
        </div>
      <% end %>
    </div>
    <div class="group">
      <%= f.fields_for :group_schedules do |g| %>
        <%= f.label 'グループ' %>
        <%= g.collection_check_boxes :group_ids, Group.all, :id, :name %>
      <% end %>
    </div>
    <div class="btns">
      <%= f.submit '登録', class:"submit" %>
    </div>
  <% end %>
  </div>
  <div id="calendar"></div>
</div>

app/views/schedules/new.html.erb
<%# 2022/11/15 トップページから予定追加機能を追加したため使用していないが、念の為記述はそのまま残す。 %>
<div class="wrapper">
  <%= form_with model:@new_schedule, url: schedules_path, local: true do |f| %>
    <div class="schedule">
      <%= f.label '予定名' %>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="start">
      <%= f.label '開始日時' %>
      <%= f.datetime_local_field :start %>
    </div>
    <div class="end">
      <%= f.label '終了日時' %>
      <%= f.datetime_local_field :end %>
    </div>
    <div class="place">
      <%= f.label '場所' %>
      <%= f.text_field :place %>
    </div>
    <div class="description">
      <%= f.label 'メモ' %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.fields_for :user_schedules do |u| %>
        <div class="editors">
          <%= f.label '参加管理者' %>
          <%= u.collection_check_boxes :user_ids, @editors, :id, :name%>
        </div>
        <div class="ordinaly_users">
          <%= f.label '参加利用者' %>
          <%= u.collection_check_boxes :user_ids, @ordinaly_users, :id, :name%>
        </div>
      <% end %>
    </div>
    <div class="group">
      <%= f.fields_for :group_schedules do |g| %>
        <%= f.label 'グループ' %>
        <%= g.collection_check_boxes :group_ids, Group.all, :id, :name %>
      <% end %>
    </div>
    <div class="btns">
      <%= f.submit '登録', class:"submit" %>
    </div>
  <% end %>
</div>

app/views/schedules/show.html.erb
<h1>schedules # show</h1>

<p>
  予定名：<%= @schedule.name %>
</p>
<p>
  開始日時：<%= @schedule.start %>
</p>
<p>
  終了日時：<%= @schedule.end %>
</p>
<p>
  参加者：
  <% @schedule.users.each do |u| %>
    <%= u.name %>
  <% end %>
</p>
<p>
  グループ：
  <% @schedule.groups.each do |g| %>
    <%= g.name %>
  <% end %>
</p>
<p>
  場所：<%= @schedule.place %>
</p>
<p>
  メモ：<%= @schedule.description %>
</p>
<p><%= link_to '編集する', edit_schedule_path(@schedule.id) %></p>